### ISSUE TITLE
External Player Button does not render in Plex Web Player Version 4.76.1

### ISSUE THREAD

**Issue by hestenet** [Plex-External-Player-PotPlayer/Script#2]
After recent updates to Plex, especially the web player Version 4.76.1 - the external potplayer button does not render anymore. No other changes to the user script or extension.

**Comment by dm4k3r** [comment]
You need the editor in Tampermonkey
`var NewDisclosureArrowButton_e = jQuery("[class^='DisclosureArrowButton-disclosureArrowButton-1ReSRg Link-link-3cHWtJ DisclosureArrowButton-medium-1crRwr DisclosureArrowButton-isSelected-1637uR Link-link-3cHWtJ Link-default-5Qrl3D Link-isSelected-3BPEaB']")`
changed to
`var NewDisclosureArrowButton_e = jQuery("[class^='DisclosureArrowButton-disclosureArrowButton-x_5Y9W Link-link-SxPFpG DisclosureArrowButton-medium-OfMgTz DisclosureArrowButton-isSelected-NHMC06 Link-link-SxPFpG Link-default-BXtKLo Link-isSelected-x0P_By']")`
It works fine, this is my plan.

**Comment by Relax-87** [comment]
> 你需要将篡改猴子的编辑器更改为它工作正常，这是我的计划。`var NewDisclosureArrowButton_e = jQuery("[class^='DisclosureArrowButton-disclosureArrowButton-1ReSRg Link-link-3cHWtJ DisclosureArrowButton-medium-1crRwr DisclosureArrowButton-isSelected-1637uR Link-link-3cHWtJ Link-default-5Qrl3D Link-isSelected-3BPEaB']")``var NewDisclosureArrowButton_e = jQuery("[class^='DisclosureArrowButton-disclosureArrowButton-x_5Y9W Link-link-SxPFpG DisclosureArrowButton-medium-OfMgTz DisclosureArrowButton-isSelected-NHMC06 Link-link-SxPFpG Link-default-BXtKLo Link-isSelected-x0P_By']")`

我很抱歉。 由于工作原因，无法关注本项目的预更新。 如果需要，可以 fork 这个项目以进行后续更新。

**Comment by hestenet** [comment]
@dm4k3r - What method did you use in the inspector to identify the changed classes? They've changed again and I'm finding it pretty tedious to find them..

**Comment by Relax-87** [comment]
> @dm4k3r - What method did you use in the inspector to identify the changed classes? They've changed again and I'm finding it pretty tedious to find them..

I don't understand what you mean, what are you trying to get? A web version of plex? Or some other element?

**Comment by hestenet** [comment]
I am looking for the best way to use the browser inspector to find the classes that need to be updated in the tamper monkey script, so I can keep it up to date myself. Since recent updates have broken the script again.

**Comment by Relax-87** [comment]
> I am looking for the best way to use the browser inspector to find the classes that need to be updated in the tamper monkey script, so I can keep it up to date myself. Since recent updates have broken the script again.

If I understand correctly, you want to dynamically find the classname and then you don't have to worry about his web version changing. This enables automatic tracking of bound buttons. If so, it may be complicated because the classname of the plex is obfuscated, you can find the classname to append the binding according to the current version of the layout.
my idea is this
Example:
``` HTML
<div class="MetadataPosterListItem-card-BfbXw7 PosterCard-card-BRB1k_" >...</div>
```
(-BfbXw7,-BRB1k_) makes them change every time they upgrade the web version, so we can ignore this part. Only perform fuzzy matching on the following part
MetadataPosterListItem-card-
PosterCard-card-
Find related elements by fuzzy matching.
However, even if the method I mentioned above can locate the classname you want, it still needs to be screened and tested again.
Even so, when a major version is updated, the part where the classname is not confused may change its name, but at least one modification can be guaranteed, and it can be used for a long time without updating every version number

There may be certain errors in our communication language and grammar, please understand if there is any misunderstanding!

**Comment by hestenet** [comment]
That's helpful, thank you!

**Comment by Relax-87** [comment]
> That's helpful, thank you!

I'm glad I understood your question correctly and at the same time gave you helpful information. So if there is no other doubt I will close the issuse for now. If something else happens that needs to be communicated then you can bring up the issuse again.
